#pragma once

#define STEPPER_1_PULSE_PIN 5
#define STEPPER_2_PULSE_PIN 7
#define STEPPER_3_PULSE_PIN 11

#define STEPPER_1_DIR_PIN 49
#define STEPPER_2_DIR_PIN 53
#define STEPPER_3_DIR_PIN 51

#define COMMON_ENA_PIN 64

#define ENCODER_1_PIN 61
#define ENCODER_2_PIN 60 
#define ENCODER_3_PIN 59

